/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package gui;

import conexionMySql.ConexMySql;
import dao.HFacturaDAO;
import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

public class AuditoriaFacturaGUI extends javax.swing.JInternalFrame {

    DefaultTableModel objDtm;
    HFacturaDAO objHFacturaDAO = new HFacturaDAO();
    ResultSet rsFactura;
    SimpleDateFormat objDateFormat = new SimpleDateFormat("yyyy-MM-dd");

    public AuditoriaFacturaGUI() {
        initComponents();
        setSize(719, 380);
        setVisible(true);
        objDtm = (DefaultTableModel) jtblRegistros.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jdatFin = new com.toedter.calendar.JDateChooser();
        jdatInicio = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblRegistros = new javax.swing.JTable();
        jbtnBuscar = new javax.swing.JButton();
        jbtnImprimir = new javax.swing.JButton();
        jbtnSalir = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("FECHA FIN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jLabel3.setText("FECHA INICIO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        getContentPane().add(jdatFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 160, -1));
        getContentPane().add(jdatInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 160, -1));

        jtblRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FACTURA", "FECHA", "CLIENTE", "EMPLEADO", "TOTAL", "TRANSA", "USUARIO", "FECHA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblRegistros);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 650, 180));

        jbtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Buscar.png"))); // NOI18N
        jbtnBuscar.setText("BUSCAR");
        jbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 120, 45));

        jbtnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/factura_1.png"))); // NOI18N
        jbtnImprimir.setText("IMPRIMIR");
        jbtnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 120, 45));

        jbtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/salir.png"))); // NOI18N
        jbtnSalir.setText("SALIR");
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 120, 45));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void jbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarActionPerformed
        try {
            limpiarJTable();
            String fechaInicio = objDateFormat.format(jdatInicio.getDate());
            String fechaFin = objDateFormat.format(jdatFin.getDate());
            rsFactura = objHFacturaDAO.buscarPorFecha(fechaInicio, fechaFin);
            while (rsFactura.next()) {
                Object[] registro = {rsFactura.getInt(1), rsFactura.getDate(2), rsFactura.getString(4),
                    rsFactura.getString(6), rsFactura.getDouble(10), rsFactura.getString(13), rsFactura.getString(14),
                    rsFactura.getString(15)};
                objDtm.addRow(registro);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jbtnBuscarActionPerformed

    private void jbtnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnImprimirActionPerformed
        try {
            String fechaInicio = objDateFormat.format(jdatInicio.getDate());
            String fechaFin = objDateFormat.format(jdatFin.getDate());

            Connection cn = ConexMySql.getInstance().getConnection();
            String direccion = System.getProperty("user.dir") + "\\src\\reporte\\repAuditoriaFactura.jrxml";
            JasperReport reporte = JasperCompileManager.compileReport(direccion);

            Map parametro = new HashMap();
            parametro.put("fechaInicio", fechaInicio);
            parametro.put("fechaFin", fechaFin);

            JasperPrint mostrarReporte = JasperFillManager.fillReport(reporte, parametro, cn);
            JasperViewer view = new JasperViewer(mostrarReporte, false);
            view.setTitle("Reporte de Factura");
            view.setExtendedState(MAXIMIZED_BOTH);
            view.setVisible(true);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jbtnImprimirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbtnBuscar;
    private javax.swing.JButton jbtnImprimir;
    private javax.swing.JButton jbtnSalir;
    private com.toedter.calendar.JDateChooser jdatFin;
    private com.toedter.calendar.JDateChooser jdatInicio;
    private javax.swing.JTable jtblRegistros;
    // End of variables declaration//GEN-END:variables

    private void limpiarJTable() {
        while (objDtm.getRowCount() > 0) {
            objDtm.removeRow(0);
        }
    }
}
