/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package gui;

import conexionMySql.ConexMySql;
import dao.DetalleFacturaDAO;
import dao.FacturaDAO;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import to.DetalleFacturaTO;
import to.FacturaTO;

/**
 *
 * @author Merca
 */
public class FacturaGUI extends javax.swing.JInternalFrame {

    DefaultTableModel objDtm;
    boolean sw;
    double precio;
    int cantidad;
    double importe;
    double subtotal;
    double igv;
    double total;
    FacturaDAO objFacturaDAO = new FacturaDAO();
    DetalleFacturaDAO objDetalleFacturaDAO = new DetalleFacturaDAO();

    public FacturaGUI() {
        initComponents();
        setSize(842, 650);
        setVisible(true);
        objDtm = (DefaultTableModel) jtblRegistro.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtFecha = new javax.swing.JTextField();
        jtxtFactura = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtxtCodCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtNombCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtDirecion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxtCiudad = new javax.swing.JTextField();
        jtxtCelular = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jbtnCliente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jtxtCodEmpleado = new javax.swing.JTextField();
        jtxtNombEmpleado = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtxtPaterno = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtxtMaterno = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jbtnNuevo1 = new javax.swing.JButton();
        jbtnGrabar1 = new javax.swing.JButton();
        jbtnCancelar1 = new javax.swing.JButton();
        jbtnSalir1 = new javax.swing.JButton();
        jbtnEmpleado = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jtxtCodProducto = new javax.swing.JTextField();
        jtxtPrecio = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtxtCantidad = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtxtImporte = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jbtnAgregar = new javax.swing.JButton();
        jbtnEliminar = new javax.swing.JButton();
        jbtnProducto = new javax.swing.JButton();
        jtxtNombProducto1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblRegistro = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jbtnNuevo = new javax.swing.JButton();
        jbtnGrabar = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();
        jbtnSalir = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jtxtSubtotal = new javax.swing.JTextField();
        jtxtIGV = new javax.swing.JTextField();
        jtxtTotal = new javax.swing.JTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("STORE S.A.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setText("Fecha");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, -1));

        jLabel4.setText("Factura");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, -1, -1));
        getContentPane().add(jtxtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 130, -1));
        getContentPane().add(jtxtFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 130, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("CODIGO CLIENTE");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));
        jPanel1.add(jtxtCodCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 170, -1));

        jLabel6.setText("NOMBRE CLIENTE");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));
        jPanel1.add(jtxtNombCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 590, -1));

        jLabel7.setText("DIRECCION");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));
        jPanel1.add(jtxtDirecion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 590, -1));

        jLabel8.setText("CIUDAD");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));
        jPanel1.add(jtxtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 240, -1));
        jPanel1.add(jtxtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 240, -1));

        jLabel9.setText("CELULAR");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, -1));

        jbtnCliente.setText("...");
        jbtnCliente.setEnabled(false);
        jbtnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClienteActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 40, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 830, 130));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("COD EMPLEADO");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));
        jPanel3.add(jtxtCodEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 160, -1));
        jPanel3.add(jtxtNombEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 160, -1));

        jLabel11.setText("NOMBRE");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));
        jPanel3.add(jtxtPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 160, -1));

        jLabel12.setText("PATERNO");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));
        jPanel3.add(jtxtMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 160, -1));

        jLabel13.setText("MATERNO");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, -1, -1));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jbtnNuevo1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jbtnNuevo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/nuevo.png"))); // NOI18N
        jbtnNuevo1.setText("NUEVO");

        jbtnGrabar1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jbtnGrabar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/grabar.png"))); // NOI18N
        jbtnGrabar1.setText("GRABAR");

        jbtnCancelar1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jbtnCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cancelar.png"))); // NOI18N
        jbtnCancelar1.setText("CANCELAR");

        jbtnSalir1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jbtnSalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/salir.png"))); // NOI18N
        jbtnSalir1.setText("SALIR");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jbtnNuevo1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnGrabar1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNuevo1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnGrabar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 570, 90));

        jbtnEmpleado.setText("...");
        jbtnEmpleado.setEnabled(false);
        jbtnEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEmpleadoActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 40, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, 80));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setText("COD PRODUCTO");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));
        jPanel4.add(jtxtCodProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 160, -1));
        jPanel4.add(jtxtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 160, -1));

        jLabel15.setText("PRECIO");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jtxtCantidad.setEditable(false);
        jtxtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCantidadActionPerformed(evt);
            }
        });
        jPanel4.add(jtxtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 160, -1));

        jLabel16.setText("CANTIDAD");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));
        jPanel4.add(jtxtImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 160, -1));

        jLabel17.setText("IMPORTE");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, -1, -1));

        jbtnAgregar.setText("AGREGAR");
        jbtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgregarActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        jbtnEliminar.setText("ELIMINAR");
        jbtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEliminarActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        jbtnProducto.setText("...");
        jbtnProducto.setEnabled(false);
        jbtnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnProductoActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 40, -1));
        jPanel4.add(jtxtNombProducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 630, -1));

        jLabel21.setText("NOMBRE");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 830, 140));

        jtblRegistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE", "PRECIO", "CANTIDAD", "IMPORTE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblRegistro);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 830, 110));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jbtnNuevo.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jbtnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/nuevo.png"))); // NOI18N
        jbtnNuevo.setText("NUEVO");
        jbtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNuevoActionPerformed(evt);
            }
        });

        jbtnGrabar.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jbtnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/grabar.png"))); // NOI18N
        jbtnGrabar.setText("GRABAR");
        jbtnGrabar.setEnabled(false);
        jbtnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGrabarActionPerformed(evt);
            }
        });

        jbtnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jbtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cancelar.png"))); // NOI18N
        jbtnCancelar.setText("CANCELAR");
        jbtnCancelar.setEnabled(false);
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });

        jbtnSalir.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jbtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/salir.png"))); // NOI18N
        jbtnSalir.setText("SALIR");
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jbtnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 570, 90));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setText("SUBTOTAL");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 10, -1, -1));

        jLabel19.setText("IGV");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 38, -1, -1));

        jLabel20.setText("TOTAL");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 66, -1, -1));
        jPanel6.add(jtxtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 7, 120, -1));
        jPanel6.add(jtxtIGV, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 35, 120, -1));
        jPanel6.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 63, 120, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 520, 250, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClienteActionPerformed
        MenuGUI.desktopPane.add(new BuscarClienteGUI());
    }//GEN-LAST:event_jbtnClienteActionPerformed

    private void jbtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNuevoActionPerformed
        habilitaControles(true);
    }//GEN-LAST:event_jbtnNuevoActionPerformed

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        habilitaControles(false);
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void jbtnEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEmpleadoActionPerformed
        MenuGUI.desktopPane.add(new BuscarEmpleadoGUI());
    }//GEN-LAST:event_jbtnEmpleadoActionPerformed

    private void jbtnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnProductoActionPerformed
        MenuGUI.desktopPane.add(new BuscarProductoGUI());
    }//GEN-LAST:event_jbtnProductoActionPerformed

    private void jtxtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCantidadActionPerformed
        precio = Double.parseDouble(jtxtPrecio.getText().trim());
        cantidad = Integer.parseInt(jtxtCantidad.getText().trim());
        importe = precio * cantidad;
        jtxtImporte.setText(String.format("%.2f", importe));
    }//GEN-LAST:event_jtxtCantidadActionPerformed

    private void jbtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgregarActionPerformed
        try {
            if (importe == 0) {
                JOptionPane.showMessageDialog(rootPane, "Seleccione un Producto o falta ingresar cantidad");
            } else {
                int cont = 0;
                boolean sw = false;
                Object[] registro = {jtxtCodProducto.getText(), jtxtNombProducto1.getText(),
                    precio, cantidad, importe};
                if (objDtm.getRowCount() == 0) {
                    objDtm.addRow(registro);
                } else {
                    int xid_producto = Integer.parseInt(jtxtCodProducto.getText());
                    while (cont < objDtm.getRowCount()) {
                        if (xid_producto == Integer.parseInt(objDtm.getValueAt(cont, 0).toString())) {
                            JOptionPane.showMessageDialog(rootPane, "El producto ya existe");
                            cont = objDtm.getRowCount();
                            sw = true;
                        }
                        cont++;
                    }
                    if (!sw) {
                        objDtm.addRow(registro);
                    }
                }
            }
            limpiarProducto();
            calcularDatos();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jbtnAgregarActionPerformed

    private void jbtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarActionPerformed
        objDtm.removeRow(jtblRegistro.getSelectedRow());
        calcularDatos();
    }//GEN-LAST:event_jbtnEliminarActionPerformed

    private void jbtnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGrabarActionPerformed
        try {
            int xid_facrura;
            FacturaTO objFacturoTO = new FacturaTO();
            objFacturoTO.setId_cliente(Integer.parseInt(jtxtCodCliente.getText()));
            objFacturoTO.setId_empleado(Integer.parseInt(jtxtCodEmpleado.getText()));
            objFacturoTO.setStot_fact(subtotal);
            objFacturoTO.setIgv_fact(igv);
            objFacturoTO.setTota_fact(total);
            objFacturaDAO.insert(objFacturoTO);
            xid_facrura = objFacturaDAO.obtenerIdFactura();
            int filas = objDtm.getRowCount();
            for (int i = 0; i < filas; i++) {
                DetalleFacturaTO objDetalleFacturaTO = new DetalleFacturaTO();
                objDetalleFacturaTO.setId_factura(xid_facrura);
                objDetalleFacturaTO.setId_producto(Integer.parseInt(jtblRegistro.getValueAt(i, 0).toString()));
                objDetalleFacturaTO.setPrec_prod(Double.parseDouble(jtblRegistro.getValueAt(i, 2).toString()));
                objDetalleFacturaTO.setCantidad(Integer.parseInt(jtblRegistro.getValueAt(i, 3).toString()));
                objDetalleFacturaTO.setImporte(Double.parseDouble(jtblRegistro.getValueAt(i, 4).toString()));
                objDetalleFacturaDAO.insert(objDetalleFacturaTO);
            }
            habilitaControles(false);
            limpiaControles();
            JOptionPane.showMessageDialog(rootPane, "Registro Grabado");
            try {
                Connection cn = ConexMySql.getInstance().getConnection();
                String direccion = System.getProperty("user.dir") + "\\src\\reporte\\repFactura.jrxml";
                JasperReport reporte = JasperCompileManager.compileReport(direccion);
                Map parametros = new HashMap();
                parametros.put("p_id_factura", objFacturaDAO.obtenerIdFactura());
                JasperPrint mostrarReporte = JasperFillManager.fillReport(reporte, parametros, cn);
                JasperViewer view = new JasperViewer(mostrarReporte, false);
                view.setTitle("Reporte de Factura");
                view.setExtendedState(MAXIMIZED_BOTH);
                view.setVisible(true);
                
            } catch (Exception e) {
                System.out.println(e);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jbtnGrabarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAgregar;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnCancelar1;
    private javax.swing.JButton jbtnCliente;
    private javax.swing.JButton jbtnEliminar;
    private javax.swing.JButton jbtnEmpleado;
    private javax.swing.JButton jbtnGrabar;
    private javax.swing.JButton jbtnGrabar1;
    private javax.swing.JButton jbtnNuevo;
    private javax.swing.JButton jbtnNuevo1;
    private javax.swing.JButton jbtnProducto;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JButton jbtnSalir1;
    private javax.swing.JTable jtblRegistro;
    public static javax.swing.JTextField jtxtCantidad;
    public static javax.swing.JTextField jtxtCelular;
    public static javax.swing.JTextField jtxtCiudad;
    public static javax.swing.JTextField jtxtCodCliente;
    public static javax.swing.JTextField jtxtCodEmpleado;
    public static javax.swing.JTextField jtxtCodProducto;
    public static javax.swing.JTextField jtxtDirecion;
    private javax.swing.JTextField jtxtFactura;
    private javax.swing.JTextField jtxtFecha;
    private javax.swing.JTextField jtxtIGV;
    public static javax.swing.JTextField jtxtImporte;
    public static javax.swing.JTextField jtxtMaterno;
    public static javax.swing.JTextField jtxtNombCliente;
    public static javax.swing.JTextField jtxtNombEmpleado;
    public static javax.swing.JTextField jtxtNombProducto1;
    public static javax.swing.JTextField jtxtPaterno;
    public static javax.swing.JTextField jtxtPrecio;
    private javax.swing.JTextField jtxtSubtotal;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
    private void habilitaControles(boolean b) {
        jbtnCliente.setEnabled(b);
        jbtnEmpleado.setEnabled(b);
        jbtnProducto.setEnabled(b);
        jtxtCantidad.setEditable(b);
        jbtnGrabar.setEnabled(b);
        jbtnCancelar.setEnabled(b);
        jbtnEliminar.setEnabled(b);
        jbtnNuevo.setEnabled(!b);
        jbtnSalir.setEnabled(!b);
    }

    private void limpiaControles() {
        limpiarJtable();
        JTextField[] arrayJtextFields = {jtxtCantidad, jtxtCelular, jtxtCiudad, jtxtCodCliente,
            jtxtCodEmpleado, jtxtCodProducto, jtxtDirecion, jtxtFactura, jtxtFecha, jtxtIGV, jtxtImporte, jtxtMaterno,
            jtxtNombCliente, jtxtNombEmpleado, jtxtPrecio, jtxtPaterno, jtxtSubtotal, jtxtTotal};
        for (JTextField objTextField : arrayJtextFields) {
            objTextField.setText(null);
        }
    }

    private void limpiarJtable() {
        while (objDtm.getRowCount() > 0) {
            objDtm.removeRow(0);
        }
    }

    private void limpiarProducto() {
        jtxtCodProducto.setText(null);
        jtxtNombProducto1.setText(null);
        jtxtPrecio.setText(null);
        jtxtCantidad.setText(null);
        jtxtImporte.setText(null);
        precio = 0;
        cantidad = 0;
        importe = 0;
    }

    private void calcularDatos() {
        subtotal = 0;
        igv = 0;
        total = 0;
        int filas = objDtm.getRowCount();
        for (int i = 0; i < filas; i++) {
            total += Double.parseDouble(objDtm.getValueAt(i, 4).toString());
        }
        subtotal = total / 1.18;
        igv = total - subtotal;
        jtxtSubtotal.setText(String.format("%.2f", subtotal));
        jtxtIGV.setText(String.format("%.2f", igv));
        jtxtTotal.setText(String.format("%.2f", total));
    }
}
